### ISSUE TITLE
don't print vacuous cofibrations

### ISSUE THREAD

**Issue by ivoysey** [jonsterling/cooltt#38]
right now, given the input
```
def formation : {
  (A : dim -> univ) (a : A 0) (b : A 1) -> univ
} = {
  \A a b =>  -- normal lambda form
  path A a ?  -- this is the new form for paths
}
```
the pretty printer gives the following information for the hole
```
Emitted hole:        
  A : (-> [_x : dim]  univ)
  a : (el (A 0))
  b : (el (A 1))
  _x : dim
  _x₁ : (prf (or (= _x 0) (= _x 1)))
  _x₂ : (prf (= _x 1))
  |- ? : (el (A _x)) [_x₃ : (= _x 0) => []]
```
This is correct but somewhat misleading. The constraint `[_x₃ : (= _x 0) => []]` is satisfied vacuously: `_x = 1` is in the context and equality of dimensions is decidable, we know that `_x` cannot ever be zero. Therefore any `el (A _x)` will do because they all satisfy that constraint definitionally, which is to say any `el (A 1)` will do, including the one in the context `b`.

A better output might look like
```
Emitted hole:        
  A : (-> [_x : dim]  univ)
  a : (el (A 0))
  b : (el (A 1))
  _x : dim
  _x₁ : (prf (or (= _x 0) (= _x 1)))
  _x₂ : (prf (= _x 1))
  |- ? : (el (A _x))
```
An _even better_ output might even look like 
```
Emitted hole:        
  A : (-> [_x : dim]  univ)
  a : (el (A 0))
  b : (el (A 1))
  _x : dim
  _x₁ : (prf (or (= _x 0) (= _x 1)))
  _x₂ : (prf (= _x 1))
  |- ? : (el (A 1))
```
but that's a different issue.

**Comment by ivoysey** [comment]
Sage advice from Jon about tackling this:

> https://github.com/jonsterling/cooltt/blob/path-code/src/lib/Refiner.ml#L27
This is the function that creates a top-level hole; the arguments (tp, phi, clo) are doing the following: tp is the type of the hole, phi is the cofibration you are constraining along, and clo is a closure representing a partial element “_ : phi !- p : tp”.
The thing you would want to do is check whether the cofibration phi is false (this can be done using some operations in the monad I believe), and if it is false, replace phi with Cof.bot before proceeding.

**Comment by jonsterling** [comment]
I suggest writing a function to "normalize" cofibrations (in the `EM.m` monad), and then this function can be called by `make_hole` as discussed above. Currently, this normalization function might just only look for vacuous cofibrations and replace them by `Cof.bot` (which will have the desired result of this ticket), but in the future we may even augment the function to produce equivalent-but-more-regular-or-more-optimized representatives of the same equivalence class.

**Comment by ivoysey** [comment]
How much of a rabbit hole do you think it is to do some kind of lightweight rewriting? Like the above instance of "oh i know that `x=1` so i'll do `[1/x]` on the goal type" is itself kind of benign (and I think helpful to a user) but I don't know how much of a quagmire that really is. My hope is "some but not much" exactly because the theory of dimension equality is decidable in open contexts, but I don't know if I'm right or not.

**Comment by jonsterling** [comment]
Good question; for the case of choosing a more intuitive representative of the equivalence class, we can probably do this without too much difficulty by changing the implementation of `quote_dim`, specifically the `DimVar` clause.

The logic there could be changed to:

If we're looking at `r === DimVar lvl`, then let's fire off a query to the cofibration environment to find out if `r=0` is true, and if so return `0` literally, and the same for `r=1`, and only otherwise quote the variable.

**Comment by jonsterling** [comment]
This line gives an example of how to branch on whether two dimensions are equal in the appropriate monad:

https://github.com/jonsterling/cooltt/blob/90ddfa6d457d0b3e29ef911b12725db26b65f0b7/src/lib/Nbe.ml#L1102

**Comment by cangiuli** [comment]
Related: should we have surface syntax for the true cofibration? (Right now we have some tests that explicitly mention `0=0`.)

**Comment by jonsterling** [comment]
sure!

**Comment by ivoysey** [comment]
@cangiuli I think you're probably referring to this one?
```
def testing : {
  (Z : univ) (A : univ) (B : A -> univ) (p : Z -> (x : A) * B x) ->
  (z : Z) -> (x : sub A {0==0} {fst {p z}}) * B x
} = {
  \_ _ _ p => p
}

normalize testing
```
What would you want that to look like?

**Comment by cangiuli** [comment]
The Unicode name for `0=0` should be `⊤`. I don't know what would be a good plain text name because it seems awkward to reserve `true` or `T` or the like; open to suggestions there.

**Comment by jonsterling** [comment]
What about `#t` / `#f`? 😎

**Comment by ivoysey** [comment]
@jonsterling at the line you pointed out, `phi` has type `D.cof` which makes me want to write `norm : D.cof -> D.cof`. I'm a little puzzled, though, because I feel like what I'm looking for is instances of `CofAbort`, though, because that's what prints as `[]`. I guess said differently, just a cofibration being `x = 0` isn't enough to know that it's OK to replace it with `Cof.bot`; it's that it's mapped* to an abort and I don't really know where that mapping is happening.

*"mapped" is probably the wrong word here but I am being led astray by your `=>` notation in the output.

**Comment by jonsterling** [comment]
So, what is happening is: there are many cofibrations that are definitionally equal to `Cof.bot` but not literally `Cof.bot`. Anything that implies `0=1` for instance. Under all of these false cofibrations, the normal form of a term is `[]`, but the printer cannot be expected to check if a cofibration is false. So, if we want the printer to do something smart in that case, we need to give it something that is obviously false (`Cof.bot`).

**Comment by ivoysey** [comment]
Yeah, I think I understand that strategy, but maybe I don't because I'm still confused. In the output `(el (A _x)) [_x₃ : (= _x 0) => []]`, the cofibration is just `(= _x 0)`, right? Represented by (roughly) `Cof.Cof(Cof.eq(Var x, DomainData.Dom0))`? That in and of itself contradictory, it's only because in the context of the hole we have `(prf (= _x 1))` that we know that's impossible to satisfy.

So maybe a better question is: does normalization of a cofibration have type `D.cof -> D.cof` or `ctx -> D.cof -> D.cof`? And if it's the latter, I guess the context is being reified into the ∏ that's getting computed by traversing the cells in that function? (https://github.com/jonsterling/cooltt/blob/master/src/lib/Refiner.ml#L32)

**Comment by jonsterling** [comment]
Oh, now I see the thing I need to explain ;-) 

You need `D.cof -> D.cof m`; the monad has enough state in it to let you literally ask whether `phi` implies `0=1`. The relevant functions are `EM.lift_cmp @@ CmpM.test_sequent [phi] (Cof.eq Cof.dim0 Cof.dim1)` or something like this.

**Comment by ivoysey** [comment]
oh oh, ok. i see which tree you're barking up and it is not the same as the one i am.

**Comment by ivoysey** [comment]
everything discussed in here was addressed in a PR that's merged into master, so i will now close this issue.
